[package]
name = "cppm"
version = "2.2.2"
edition = "2021"
authors = ["Maou Shimazu <maoushimazu@protonmail.com>"]
description = "A C++ Project Manager"
readme = "README.md"
repository = "https://github.com/Maou-Shimazu/Cpp-Project-Manager"
license = "MIT"
license-file = "LICENSE"
keywords = ["cli", "terminal", "tui"]

[dependencies]
colored = "2"
dirs = "4.0.0"
envmnt = "^0.10.0"
fsio = "0.3.0"
configparser = "3.0.0"
clap = "3.1.12"