[package]
name = "cppm"
version = "3.0.0"
edition = "2021"
authors = ["Maou Shimazu <maoushimazu@protonmail.com>"]
description = "A C++ Project Manager"
readme = "README.md"
repository = "https://github.com/Maou-Shimazu/Cpp-Project-Manager"
license = "MIT"
keywords = ["cli", "terminal", "tui"]

[dependencies]
colored = "2"
dirs = "4.0.0"
envmnt = "^0.10.0"
fsio = "0.3.0"
serde = { version = "1.0.137", features = ["derive"] }
toml = "0.5.9"
walkdir = "2.3.2"