[package]
name = "cppm"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
dirs = "4.0.0"
argparse = "0.2.2"
envmnt = "^0.10.0"
fsio = "0.3.0"
configparser = "3.0.0"