name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release-amd64:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --release --bins

      - name: Rename executable (linux)
        if: matrix.os == 'ubuntu-latest'
        run: mv target/release/cppm target/release/cppm-linux-amd64

      - name: Rename executable (mac)
        if: matrix.os == 'macos-latest'
        run: mv target/release/cppm target/release/cppm-macos-amd64

      - name: Rename executable (windows)
        if: matrix.os == 'windows-latest'
        run: Rename-Item .\target\release\cppm.exe cppm-windows-amd64.exe

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/cppm*64?(.exe)
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-aarch64:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - name: macos-aarch64
            os: macos-latest
            target: aarch64-apple-darwin

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          default: true
          override: true

      - name: Build
        run: cargo build --release --bins --target ${{ matrix.target }}

      - name: Rename executable
        run: mv target/${{ matrix.target }}/release/cppm target/${{ matrix.target }}/release/cppm-${{ matrix.name }}

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: target/${{ matrix.target }}/release/cppm*64?(.exe)
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
