name: Release

on:
  push:
    branches:
      - main

jobs:
  release-amd64:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --release --bins

      - name: Rename executable (linux)
        if: matrix.os == 'ubuntu-latest'
        run: mv target/release/cppm target/release/cppm-linux-amd64

      - name: Rename executable (mac)
        if: matrix.os == 'macos-latest'
        run: mv target/release/cppm target/release/cppm-macos-amd64

      - name: Rename executable (windows)
        if: matrix.os == 'windows-latest'
        run: Rename-Item .\target\release\cppm.exe cppm-windows-amd64.exe

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/cppm*64?(.exe)
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-aarch64:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false # for testing only, remove when finished
      matrix:
        include:
          - name: linux-aarch64
            os: ubuntu-latest
            linker-package: gcc-aarch64-linux-gnu
            linker: aarch64-linux-gnu-gcc
            target: aarch64-unknown-linux-gnu

          - name: macos-aarch64
            os: macos-latest
            target: aarch64-apple-darwin

          # - name: windows-aarch64
          #   os: windows-latest
          #   target: aarch64-pc-windows-msvc

    steps:
      - uses: actions/checkout@v3

      - name: Install linker (linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install ${{ matrix.linker-package }}
          mkdir -p .cargo
          echo [targret.${{ matrix.target }}] > .cargo/config
          echo linker '"'${{ matrix.linker }}'"' >> .cargo/config

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          default: true
          override: true

      - name: Build
        run: cargo build --release --bins --target ${{ matrix.target }}

      - name: Rename executable (*nix)
        if: matrix.os != 'windows-latest'
        run: mv target/${{ matrix.target }}/release/cppm target/${{ matrix.target }}/release/cppm-${{ matrix.name }}

      - name: Rename executable (windows)
        if: matrix.os == 'windows-latest'
        run: Rename-Item .\target\${{ matrix.target }}\release\cppm.exe cppm-${{ matrix.name }}.exe

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: target/${{ matrix.target }}/release/cppm*64?(.exe)
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
