name: Rust
on:
    push:
        tags:
            - "v*"
            
jobs:
  build:
    name: build for all platforms
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
      BINARY_NAME: cppm
    steps:
    - uses: actions/checkout@v2
    - name: Build-musl macOS x86
      uses: Shogan/rust-musl-action@master
      with:
        args: cargo build --target x86_64-apple-darwin --release && strip target/release/cppm && mv target/release/$cppm target/release/cppm_amd64

    - name: Build-musl Linux x86
      uses: Shogan/rust-musl-action@v1.0.2
      with:
        args: cargo build --target x86_64-unknown-linux-musl --release && strip target/release/cppm && mv target/release/$cppm target/release/cppm_amd64
        
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: |
            target/release/cppm_amd64
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
